# Generated by Django 4.1.7 on 2023-11-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMRewritingService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
